### ISSUE TITLE
empty html file

### ISSUE THREAD

**Issue by wguiraud** [iulspop/ruby_to_uml#1]
I tried using the gem with ruby-3.0.4 and ruby-3.1.2 but no luck, the returned html file is empty. 
I also tried using the gem with ruby 3.0.0 and a png file is returned. The only issue I have with this png is that the custom modules are missing. The rest of the UML is great. Thank you for your help. (I'm running PopOs! on my machine)
![uml](https://user-images.githubusercontent.com/69010265/182499324-f7baad8d-4127-4b38-9ca9-30dd690db3f1.png)

**Comment by iulspop** [comment]
Can you paste the contents of the HTML file? I tried it with Ruby 3.1.2 and it worked fine. If the codebase is large, sometimes it takes a while for the diagram to be drawn.

I'm surprised you tried it and a PNG file was created. The code only writes an HTML file. If modules are missing, perhaps the files that contain the modules are not in the folder you specified?

**Comment by wguiraud** [comment]
Here is a link towards the file I used (.rb file that contains the custom module '**Printable**' as well as all the classes) and the html you asked for. 
https://drive.proton.me/urls/1QB0DGCBQG#89owlyHYgkv5
**I was wrong the returned html file is not empty**! But when I try to open it with any browsers, it displays a blank page. What am I missing? Any tips are welcome.

**Comment by iulspop** [comment]
Hi! I downloaded the file, found the bug and released a new version of the gem that patches the bug. You can reinstall the gem and try :)

I'll explain what the bug was if you're curious. When I extracted and opened your file, the diagram was in fact not drawn. I opened the console and saw the errors `Failed to load resource: net::ERR_FILE_NOT_FOUND` and `Uncaught ReferenceError: nomnoml is not defined`. The libraries I loaded with the script tags `<script src="//unpkg.com/graphre/dist/graphre.js"></script>` and `<script src="//unpkg.com/nomnoml/dist/nomnoml.js"></script>` failed to load.

I wondered why they failed to load here when with other diagrams I had tested worked perfectly and had the same script tags to load the libraries.

Finally, I realized when I opened the HTML file in the browser through the file system (ie. at a URL like `file:///C:/Users/popiu/Desktop/New%20folder/uml_class_diagram_original.html`) it didn't work, but when the HTML file was served by a server through HTTP (for example at `http://127.0.0.1:5500/uml_class_diagram_original.html`) it did work.

The cause is the library URL I copied from the Github example had a missing scheme (nothing before the first two slashes `//unpkg.com`), so the browser implicitly assumed to fetch it by the filesystem or HTTP depending on how I opened the webpage. Of course, I couldn't find it on my filesystem.

The solution was to make the HTTPS scheme explicit. Now it works no matter how you open it!

**Comment by wguiraud** [comment]
Thank you very much for taking the time to look into it Luliu. Thank you as well for the thorough explanation.
